### ISSUE TITLE
Thank you for providing the CodeKatas

### ISSUE THREAD

**Issue by nicolibi** [AlanBarber/CodeKatas#8]
Hello,
I discovered your code kata project on GitHub and am curious to see how it can be used to improve my C# skills.
For work, I joined a C# course and am now trying to improve my skills with code katas and other exercises. So your project seems to be a very good way to start with code katas. Thanks for provididing it!
If I have a little more experience, I could also consider contributing to the project.
When the time comes, I will contact you again.

Many greetings
Nicole

**Comment by AlanBarber** [comment]
Glad you found it helpful. I really need to update it as it's very out of date :)
